import { createHash } from "node:crypto";
import { safeJsonStringify } from "../utils/safeJson.js";
export type AblationMode="REMOVE"|"ATTENUATE"|"DELAY"|"NOISE"|"REPLACE"|"DECOUPLE";
export type AblationExperiment={version:"nyxa.ablation.v1";id:string;subject:string;baselineId:string;intervention:{module:string;mode:AblationMode;strength:number};dependentMetrics:readonly string[];seed:string;authority:"none"};
export function buildAblationExperiment(input:Omit<AblationExperiment,"version"|"id"|"authority">):AblationExperiment{if(!input.subject.trim()||!input.baselineId.trim()||!input.intervention.module.trim())throw new Error("ablation_identity_invalid");if(input.intervention.strength<0||input.intervention.strength>1)throw new Error("ablation_strength_invalid");if(input.dependentMetrics.length<1||input.dependentMetrics.length>64)throw new Error("ablation_metrics_invalid");const id=`abl_${createHash("sha256").update(safeJsonStringify(input)).digest("hex").slice(0,32)}`;return{version:"nyxa.ablation.v1",id,authority:"none",...input};}
export type TerraObservation={version:"nyxa.terra.observation.v1";id:string;subject:string;perspective:string;observedAt:string;sourceRef:string;independenceClass:string;uncertainty:number;metrics:Readonly<Record<string,number>>;truthState:"OBSERVED";authority:"none"};
export function buildTerraObservation(input:Omit<TerraObservation,"version"|"id"|"truthState"|"authority">):TerraObservation{if(!input.subject.trim()||!input.perspective.trim()||!input.sourceRef.trim()||!input.independenceClass.trim())throw new Error("terra_identity_invalid");if(!Number.isFinite(input.uncertainty)||input.uncertainty<0||input.uncertainty>1)throw new Error("terra_uncertainty_invalid");const t=Date.parse(input.observedAt);if(!Number.isFinite(t))throw new Error("terra_time_invalid");for(const v of Object.values(input.metrics))if(!Number.isFinite(v))throw new Error("terra_metric_invalid");const id=`obs_${createHash("sha256").update(safeJsonStringify(input)).digest("hex").slice(0,32)}`;return{version:"nyxa.terra.observation.v1",id,truthState:"OBSERVED",authority:"none",...input};}
export type FrozenPrediction={version:"nyxa.prediction.v1";id:string;subject:string;modelRef:string;frozenAt:string;horizonAt:string;metrics:Readonly<Record<string,number>>;provenanceRefs:readonly string[];truthState:"SIMULATED";authority:"none"};
export function freezePrediction(input:Omit<FrozenPrediction,"version"|"id"|"truthState"|"authority">):FrozenPrediction{if(Date.parse(input.frozenAt)>=Date.parse(input.horizonAt))throw new Error("prediction_horizon_invalid");const id=`pred_${createHash("sha256").update(safeJsonStringify(input)).digest("hex").slice(0,32)}`;return Object.freeze({version:"nyxa.prediction.v1",id,truthState:"SIMULATED",authority:"none",...input,metrics:Object.freeze({...input.metrics}),provenanceRefs:Object.freeze([...input.provenanceRefs])});}
