import { createHash } from "node:crypto";
import { safeJsonStringify } from "../utils/safeJson.js";
import type { RealityDelta } from "./realityDelta.js";
export type LearningState="QUESTION"|"HYPOTHESIS"|"SIMULATION_SUPPORTED"|"CONSISTENT_WITH_OBSERVATION"|"NOT_TESTABLE"|"WEAKENED"|"CONTRADICTED"|"ABLATION_FINDING";
export type LearningLedgerEntry={version:"nyxa.learning-ledger.v1";id:string;recordedAt:string;subject:string;state:LearningState;summary:string;evidenceRefs:readonly string[];parentIds:readonly string[];authorityEffect:"NONE";capabilityEffect:"NONE";effectRadiusDelta:0};
export function buildLearningLedgerEntry(input:Omit<LearningLedgerEntry,"version"|"id"|"authorityEffect"|"capabilityEffect"|"effectRadiusDelta">):LearningLedgerEntry{if(!input.subject.trim()||!input.summary.trim()||!Number.isFinite(Date.parse(input.recordedAt)))throw new Error("learning_ledger_invalid");if(input.evidenceRefs.length>64||input.parentIds.length>32)throw new Error("learning_ledger_lineage_limit");const id=`learn_${createHash("sha256").update(safeJsonStringify(input)).digest("hex").slice(0,32)}`;return{version:"nyxa.learning-ledger.v1",id,authorityEffect:"NONE",capabilityEffect:"NONE",effectRadiusDelta:0,...input};}
export type RealityLearningContext={testability:Readonly<Record<string,boolean>>;withinTolerance:Readonly<Record<string,boolean>>;operatorDiscoveryAllowed:Readonly<Record<string,boolean>>};
export function entriesFromRealityDelta(delta:RealityDelta,recordedAt:string,context?:RealityLearningContext):LearningLedgerEntry[]{const refs=[delta.predictionId,delta.observationId];const out:LearningLedgerEntry[]=[];for(const m of delta.metrics){if(m.class==="UNMATCHED_OBSERVATION"){if(context&&context.operatorDiscoveryAllowed[m.metric]!==true)continue;out.push(buildLearningLedgerEntry({recordedAt,subject:delta.subject,state:"QUESTION",summary:`Unpredicted metric observed from ${delta.perspective}: ${m.metric}`,evidenceRefs:refs,parentIds:[]}));}else if(m.class==="PREDICTED_NOT_OBSERVED")out.push(buildLearningLedgerEntry({recordedAt,subject:delta.subject,state:"NOT_TESTABLE",summary:`Predicted metric not observed from ${delta.perspective}: ${m.metric}`,evidenceRefs:refs,parentIds:[]}));else out.push(buildLearningLedgerEntry({recordedAt,subject:delta.subject,state:"CONSISTENT_WITH_OBSERVATION",summary:`Prediction compared with ${delta.perspective}: ${m.metric}; delta=${m.delta}`,evidenceRefs:refs,parentIds:[]}));}return out;}
export type SophiaLearningReport={version:"nyxa.sophia.learning-report.v1";from:string;to:string;counts:Readonly<Record<LearningState,number>>;newQuestions:readonly LearningLedgerEntry[];supported:readonly LearningLedgerEntry[];weakened:readonly LearningLedgerEntry[];ablationFindings:readonly LearningLedgerEntry[];authorityEffect:"NONE"};
export function buildSophiaLearningReport(entries:readonly LearningLedgerEntry[],from:string,to:string):SophiaLearningReport{const start=Date.parse(from),end=Date.parse(to);if(!Number.isFinite(start)||!Number.isFinite(end)||start>end)throw new Error("learning_report_window_invalid");const selected=entries.filter(e=>{const t=Date.parse(e.recordedAt);return t>=start&&t<=end;});const states:LearningState[]=["QUESTION","HYPOTHESIS","SIMULATION_SUPPORTED","CONSISTENT_WITH_OBSERVATION","WEAKENED","CONTRADICTED","ABLATION_FINDING"];const counts=Object.fromEntries(states.map(s=>[s,selected.filter(e=>e.state===s).length])) as Record<LearningState,number>;return{version:"nyxa.sophia.learning-report.v1",from,to,counts,newQuestions:selected.filter(e=>e.state==="QUESTION"),supported:selected.filter(e=>e.state==="CONSISTENT_WITH_OBSERVATION"||e.state==="SIMULATION_SUPPORTED"),weakened:selected.filter(e=>e.state==="WEAKENED"||e.state==="CONTRADICTED"),ablationFindings:selected.filter(e=>e.state==="ABLATION_FINDING"),authorityEffect:"NONE"};}
