import test from 'node:test';import assert from 'node:assert/strict';
import {validateCcamEvent} from '../dist/ccam/contracts.js';import {compareJevAblation,countermeasureReady,effectDelta,trlGate} from '../dist/ccam/pipeline.js';
const e=validateCcamEvent({version:'nyxa.ccam.v0',eventId:'evt-1',scenarioId:'munich-1',source:'simulator',truthState:'SIMULATED',timestamp:'2026-10-07T12:00:00Z',actor:{id:'veh-1',kind:'vehicle'},state:{speed:8},confidence:.9,odd:{weather:'rain'},hazards:['occluded_cyclist'],provenanceRefs:['sim:run-1']});
test('simulation remains explicitly simulated with provenance',()=>{assert.equal(e.truthState,'SIMULATED');assert.deepEqual(e.provenanceRefs,['sim:run-1']);});
test('missing provenance fails closed',()=>{assert.throws(()=>validateCcamEvent({...e,provenanceRefs:[]}),/provenance_required/);});
test('Jev is ablatable and disagreement is evidence',()=>{const r=compareJevAblation(e,()=>({edgeCase:true,risk:.8,reasons:['occlusion']}),()=>({edgeCase:false,risk:.2,reasons:['triage']}));assert.equal(r.baseline.jevUsed,false);assert.equal(r.jev.jevUsed,true);assert.equal(r.disagreement,true);});
test('countermeasure requires negative-impact checks and provenance',()=>{const c={id:'cm1',scenarioId:'munich-1',action:'warn',target:'vehicle:1',scope:'scenario',expectedEffect:{collisionRisk:-.5},negativeImpactChecks:['rear_end_risk'],provenanceRefs:['analysis:1']};assert.equal(countermeasureReady(e,c),true);assert.equal(countermeasureReady(e,{...c,negativeImpactChecks:[]}),false);});
test('expected vs observed effect is measurable',()=>{const c={id:'cm1',scenarioId:'munich-1',action:'warn',target:'vehicle:1',scope:'scenario',expectedEffect:{risk:-.5},negativeImpactChecks:['rear'],provenanceRefs:['a']};assert.deepEqual(effectDelta(c,{countermeasureId:'cm1',truthState:'VERIFIED',observedEffect:{risk:-.3},negativeImpacts:[],provenanceRefs:['receipt:1']}),{risk:.2});});
test('TRL relevant environment cannot be green on simulation evidence alone',()=>{assert.equal(trlGate({stage:'RELEVANT_ENVIRONMENT',selectedByFitness:false,frozenPrediction:true,heldOutSimulator:true,outOfSimulatorValidated:false,independentEvidence:false}).green,false);assert.equal(trlGate({stage:'RELEVANT_ENVIRONMENT',selectedByFitness:false,frozenPrediction:true,heldOutSimulator:true,outOfSimulatorValidated:true,independentEvidence:true}).green,true);});
