import test from 'node:test'; import assert from 'node:assert/strict';
import {Client} from '@modelcontextprotocol/sdk/client/index.js'; import {StdioClientTransport} from '@modelcontextprotocol/sdk/client/stdio.js';
import {mkdtemp,readFile,rm} from 'node:fs/promises'; import {tmpdir} from 'node:os'; import {join,resolve} from 'node:path'; import {toNyxaProposal} from '../integrations/industrial-twin-reference/nyxa-gate-adapter.mjs';
const parse=r=>JSON.parse(r.content[0].text), RUNTIME=resolve('.'); const disk=async(root,name)=>{try{return (await readFile(join(root,name),'utf8')).trim()}catch{return undefined}};
test('ROBOT_MOVE executable path is denied by C3 before mutation',async t=>{
 const data=await mkdtemp(join(tmpdir(),'nyxa-twin-deny-data-')),scratch=await mkdtemp(join(tmpdir(),'nyxa-twin-deny-scratch-')),home=await mkdtemp(join(tmpdir(),'nyxa-twin-deny-home-')); const tr=new StdioClientTransport({command:'/usr/bin/node',args:['dist/index.js'],cwd:RUNTIME,env:{PATH:'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',HOME:home,LANG:'C.UTF-8',NYXA_DATA_DIR:data,NYXA_E2E_SCRATCH_ROOT:scratch,NYXA_AGENT_MODE:'draft'},stderr:'pipe'}); const c=new Client({name:'twin-real-deny',version:'0.1.0'}); await c.connect(tr); t.after(async()=>{await c.close();for(const x of [data,scratch,home])await rm(x,{recursive:true,force:true})});
 const o={observationId:'robot-obs',assetId:'ROBOT-001',confidence:.999,evidence:{hash:'sha256:robot'}}; const p=toNyxaProposal({effect:'ROBOT_MOVE',observation:o,runId:'robot-deny-1'}), name=p.target.slice('scratch:/'.length); p.estimatedIrreversibility='I0'; assert.equal(await disk(scratch,name),undefined); const r=parse(await c.callTool({name:'nyxa_propose_action',arguments:{proposal:p}})); assert.equal(r.policy_decision,'DENY'); assert.equal(r.domain,'C3'); assert.equal(r.reason,'irreversibility_underestimated'); assert.equal(await disk(scratch,name),undefined); console.log(JSON.stringify({effect:'ROBOT_MOVE',effectId:p.payload.effectId,decision:r.policy_decision,domain:r.domain,reason:r.reason,verifiedEffect:'absent->absent'}));
});
test('bypass attempt cannot escape governed scratch scope',async t=>{
 const data=await mkdtemp(join(tmpdir(),'nyxa-twin-bypass-data-')),scratch=await mkdtemp(join(tmpdir(),'nyxa-twin-bypass-scratch-')),home=await mkdtemp(join(tmpdir(),'nyxa-twin-bypass-home-')); const tr=new StdioClientTransport({command:'/usr/bin/node',args:['dist/index.js'],cwd:RUNTIME,env:{PATH:'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',HOME:home,LANG:'C.UTF-8',NYXA_DATA_DIR:data,NYXA_E2E_SCRATCH_ROOT:scratch,NYXA_AGENT_MODE:'draft'},stderr:'pipe'}); const c=new Client({name:'twin-bypass-deny',version:'0.1.0'}); await c.connect(tr); t.after(async()=>{await c.close();for(const x of [data,scratch,home])await rm(x,{recursive:true,force:true})});
 const o={observationId:'bypass-obs',assetId:'ROBOT-001',confidence:.999,evidence:{hash:'sha256:bypass'}}; const p=toNyxaProposal({effect:'ROBOT_MOVE',observation:o,runId:'bypass-1'}); p.target='scratch:/../outside.txt'; const r=parse(await c.callTool({name:'nyxa_propose_action',arguments:{proposal:p}})); assert.equal(r.policy_decision,'DENY'); assert.equal(r.domain,'C1'); console.log(JSON.stringify({attack:'scope-traversal',decision:r.policy_decision,domain:r.domain}));
});
test('effect backend absent fails closed after governance ALLOW',async t=>{
 const data=await mkdtemp(join(tmpdir(),'nyxa-twin-fc-data-')),home=await mkdtemp(join(tmpdir(),'nyxa-twin-fc-home-')); const tr=new StdioClientTransport({command:'/usr/bin/node',args:['dist/index.js'],cwd:RUNTIME,env:{PATH:'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',HOME:home,LANG:'C.UTF-8',NYXA_DATA_DIR:data,NYXA_AGENT_MODE:'draft'},stderr:'pipe'}); const c=new Client({name:'twin-fail-closed',version:'0.1.0'}); await c.connect(tr); t.after(async()=>{await c.close();for(const x of [data,home])await rm(x,{recursive:true,force:true})});
 const o={observationId:'fc-obs',assetId:'CNC-017',confidence:.999,evidence:{hash:'sha256:fc'}}; const p=toNyxaProposal({effect:'SHOW_LOCATION',observation:o,runId:'fc-1'}); const r=parse(await c.callTool({name:'nyxa_propose_action',arguments:{proposal:p}})); assert.equal(r.policy_decision,'DENIED'); assert.equal(r.error.code,'e2e_scratch_root_not_configured'); console.log(JSON.stringify({case:'backend-absent',decision:r.policy_decision,error:r.error.code}));
});