import test from 'node:test'; import assert from 'node:assert/strict'; import { buildOrganismSignal,canBecomeEffectProposal } from '../dist/organism/signalEnvelope.js';
const base={subject:'company:demo',provenanceRefs:['evidence:1'],parentSignalIds:[]};
test('organism signals are deterministic inert data',()=>{const a=buildOrganismSignal({...base,kind:'SIMULATION_CANDIDATE',producer:'hunter',truthState:'SIMULATED',payload:{gain:.2}});const b=buildOrganismSignal({...base,kind:'SIMULATION_CANDIDATE',producer:'hunter',truthState:'SIMULATED',payload:{gain:.2}});assert.deepEqual(a,b);assert.equal(a.authority,'none');assert.equal(a.truthState,'SIMULATED');});
test('simulation cannot launder itself into observed or verified truth',()=>{const s=buildOrganismSignal({...base,kind:'SIMULATION_CANDIDATE',producer:'hunter',truthState:'SIMULATED',payload:{claim:'x'}});assert.notEqual(s.truthState,'OBSERVED');assert.notEqual(s.truthState,'VERIFIED');assert.equal(canBecomeEffectProposal(s).allowed,true);assert.match(canBecomeEffectProposal(s).reason,/no_authority|no authority/);});
test('effect results cannot recursively authorize a new effect',()=>{const s=buildOrganismSignal({...base,kind:'EFFECT_RESULT',producer:'verification',truthState:'VERIFIED',payload:{ok:true}});assert.equal(canBecomeEffectProposal(s).allowed,false);});
test('payload changes signal identity',()=>{const a=buildOrganismSignal({...base,kind:'SECURITY_SIGNAL',producer:'antlion',truthState:'INFERRED',payload:{risk:.2}});const b=buildOrganismSignal({...base,kind:'SECURITY_SIGNAL',producer:'antlion',truthState:'INFERRED',payload:{risk:.9}});assert.notEqual(a.id,b.id);assert.notEqual(a.payloadHash,b.payloadHash);});

test('raw builder rejects simulation truth laundering',()=>{assert.throws(()=>buildOrganismSignal({kind:'SIMULATION_CANDIDATE',producer:'hunter',truthState:'VERIFIED',subject:'x',payload:{},provenanceRefs:[],parentSignalIds:[]}),/simulation_truth_laundering/);});
test('raw builder reserves VERIFIED effect results for verification',()=>{assert.throws(()=>buildOrganismSignal({kind:'EFFECT_RESULT',producer:'kernel',truthState:'VERIFIED',subject:'x',payload:{},provenanceRefs:[],parentSignalIds:[]}),/effect_result_requires_verification/);});
test('questions cannot become effect proposal inputs',()=>{const s=buildOrganismSignal({kind:'QUESTION',producer:'e0',truthState:'UNKNOWN',subject:'q',payload:{},provenanceRefs:[],parentSignalIds:[]});assert.equal(canBecomeEffectProposal(s).allowed,false);});
test('signal lineage is bounded',()=>{assert.throws(()=>buildOrganismSignal({kind:'INTERPRETATION',producer:'jev',truthState:'INFERRED',subject:'x',payload:{},provenanceRefs:[],parentSignalIds:Array.from({length:33},(_,i)=>`p${i}`)}),/lineage_limit/);});
