import test from 'node:test';import assert from 'node:assert/strict';import {openSupervisionCase,acceptReexaminationEvidence,reissuePassport,closeAfterAuthority} from '../dist/ccam/supervisionLifecycle.js';import {issueAuthorityGrant,operationallyAuthorized} from '../dist/ccam/operationalAuthority.js';
const q={requirementId:'r1',capabilityId:'urban_drive',status:'QUALIFIED',evidenceIds:['e1'],limitations:[]};
const p={schema:'nyxa.adp.v0',passportId:'p1',systemId:'ads1',manufacturer:'fixture',systemVersion:'v1',hardwareVersion:'h1',automationMode:'DRIVERLESS',odd:{city:'Munich'},qualifications:[q],status:'QUALIFIED',validFrom:'2026-10-01T00:00:00Z',authorityRefs:['old'],provenanceRefs:['fixture'],passportHash:'old-passport'};
const oldGrant=issueAuthorityGrant({grantId:'g-old',issuer:'authority',systemId:'ads1',systemVersion:'v1',passportHash:'old-passport',operatingArea:{city:'Munich'},capabilityIds:['urban_drive'],validFrom:'2026-10-01T00:00:00Z',status:'ACTIVE',legalBasisRefs:['fixture'],provenanceRefs:['fixture']});
const decision={passportRef:'old-passport',action:'SUSPEND_CAPABILITY',capabilityIds:['urban_drive'],reasons:['incident:42']};
test('incident opens targeted re-examination case',()=>{const c=openSupervisionCase(p,oldGrant,decision);assert.equal(c.status,'REEXAMINATION_REQUIRED');assert.deepEqual(c.capabilityIds,['urban_drive'])});
test('cannot reissue passport before new evidence',()=>{const c=openSupervisionCase(p,oldGrant,decision);assert.throws(()=>reissuePassport(c,p,[q],'2026-10-08T00:00:00Z'),/invalid_state/)});
test('new evidence can reissue passport but does not restore authority',()=>{let c=openSupervisionCase(p,oldGrant,decision);c=acceptReexaminationEvidence(c,['exam:new-road','exam:new-sim']);const x=reissuePassport(c,p,[{...q,evidenceIds:['new-road','new-sim']}],'2026-10-08T00:00:00Z');assert.equal(x.case.status,'AWAITING_AUTHORITY');assert.notEqual(x.passport.passportHash,p.passportHash);const op=operationallyAuthorized(x.passport,oldGrant,{systemId:'ads1',systemVersion:'v1',operatingArea:{city:'Munich'},capabilityIds:['urban_drive'],at:'2026-10-08T01:00:00Z'});assert.equal(op.authorized,false);assert.ok(op.reasons.includes('passport_binding_mismatch'))});
test('fresh authority bound to new passport closes loop',()=>{let c=openSupervisionCase(p,oldGrant,decision);c=acceptReexaminationEvidence(c,['exam:new']);const x=reissuePassport(c,p,[{...q,evidenceIds:['new']}],'2026-10-08T00:00:00Z');const g=issueAuthorityGrant({grantId:'g-new',issuer:'authority',systemId:'ads1',systemVersion:'v1',passportHash:x.passport.passportHash,operatingArea:{city:'Munich'},capabilityIds:['urban_drive'],validFrom:'2026-10-08T00:00:00Z',status:'ACTIVE',legalBasisRefs:['fixture'],provenanceRefs:['authority:new']});const closed=closeAfterAuthority(x.case,g);assert.equal(closed.status,'CLOSED');assert.equal(operationallyAuthorized(x.passport,g,{systemId:'ads1',systemVersion:'v1',operatingArea:{city:'Munich'},capabilityIds:['urban_drive'],at:'2026-10-08T01:00:00Z'}).authorized,true)});
