import {createHash} from "node:crypto";import {safeJsonStringify} from "../utils/safeJson.js";import type {MorphologyMode} from "./morphologyHomeostasis.js";
export type MorphNodeKind="CORE"|"STRUCTURE"|"COMPUTE"|"ACTUATOR"|"SENSOR"|"THERMAL"|"ENERGY"|"SURFACE";
export type MorphEdgeKind="MECHANICAL"|"DATA"|"POWER"|"FLUID";
export type MorphNode={id:string;kind:MorphNodeKind;region:string;massKg:number;capacity:number;areaM2:number};
export type MorphEdge={a:string;b:string;kind:MorphEdgeKind;capacity:number};
export type MorphGenome={version:"nyxa.morph-genome.v1";id:string;mode:MorphologyMode;generation:number;humanConformity:number;nodes:readonly MorphNode[];edges:readonly MorphEdge[];lineageRefs:readonly string[];truthState:"SIMULATED";authority:"none"};
const finite=(n:number)=>Number.isFinite(n);
export function buildMorphGenome(x:{mode:MorphologyMode;generation:number;humanConformity:number;nodes:readonly MorphNode[];edges:readonly MorphEdge[];lineageRefs:readonly string[]}):MorphGenome{
 if(!x.nodes.length||!x.edges.length||!x.lineageRefs.length||!Number.isInteger(x.generation)||x.generation<0)throw new Error("morph_genome_identity");
 if(x.mode==="H0_HUMAN"&&x.humanConformity<.98)throw new Error("morph_genome_h0_constraint");if(x.mode==="H1_BIO_INSPIRED"&&x.humanConformity<.8)throw new Error("morph_genome_h1_constraint");
 const ids=new Set<string>();for(const n of x.nodes){if(!n.id.trim()||ids.has(n.id)||![n.massKg,n.capacity,n.areaM2].every(finite)||n.massKg<0||n.capacity<0||n.areaM2<0)throw new Error("morph_genome_node");ids.add(n.id);}
 for(const e of x.edges)if(!ids.has(e.a)||!ids.has(e.b)||e.a===e.b||!finite(e.capacity)||e.capacity<0)throw new Error("morph_genome_edge");
 if(!x.nodes.some(n=>n.kind==="CORE")||!x.nodes.some(n=>n.kind==="ENERGY")||!x.nodes.some(n=>n.kind==="SURFACE"))throw new Error("morph_genome_vital_missing");
 const connected=new Set<string>([x.nodes[0]!.id]);let changed=true;while(changed){changed=false;for(const e of x.edges)if(connected.has(e.a)&&!connected.has(e.b)){connected.add(e.b);changed=true}else if(connected.has(e.b)&&!connected.has(e.a)){connected.add(e.a);changed=true;}}
 if(connected.size!==x.nodes.length)throw new Error("morph_genome_disconnected");
 const mat={...x,nodes:x.nodes.map(n=>({...n})),edges:x.edges.map(e=>({...e})),lineageRefs:[...x.lineageRefs].sort()};const id="mg_"+createHash("sha256").update(safeJsonStringify(mat)).digest("hex").slice(0,32);
 return Object.freeze({version:"nyxa.morph-genome.v1",id,...x,nodes:Object.freeze(x.nodes.map(n=>Object.freeze({...n}))),edges:Object.freeze(x.edges.map(e=>Object.freeze({...e}))),lineageRefs:Object.freeze([...x.lineageRefs]),truthState:"SIMULATED",authority:"none"});
}
export function humanGraphH0():MorphGenome{const regions=["head","torso","left_arm","right_arm","left_leg","right_leg"];const nodes:MorphNode[]=[{id:"core",kind:"CORE",region:"torso",massKg:4,capacity:1,areaM2:0},{id:"energy",kind:"ENERGY",region:"torso",massKg:10,capacity:1200,areaM2:.1},{id:"skin",kind:"SURFACE",region:"body",massKg:3,capacity:900,areaM2:1.8}];for(const r of regions)nodes.push({id:"s_"+r,kind:"STRUCTURE",region:r,massKg:r==="torso"?20:5,capacity:1,areaM2:.1},{id:"c_"+r,kind:"COMPUTE",region:r,massKg:1,capacity:r==="torso"?350:70,areaM2:.04},{id:"t_"+r,kind:"THERMAL",region:r,massKg:.5,capacity:r==="torso"?300:100,areaM2:.12},{id:"a_"+r,kind:"ACTUATOR",region:r,massKg:r==="torso"?2:1,capacity:r==="torso"?80:120,areaM2:.02},{id:"q_"+r,kind:"SENSOR",region:r,massKg:.15,capacity:40,areaM2:.02});const edges:MorphEdge[]=[];for(const n of nodes)if(n.id!=="core")edges.push({a:"core",b:n.id,kind:n.kind==="THERMAL"?"FLUID":n.kind==="ENERGY"?"POWER":"MECHANICAL",capacity:n.capacity||1});return buildMorphGenome({mode:"H0_HUMAN",generation:0,humanConformity:1,nodes,edges,lineageRefs:["human-topology:v0"]});}
export function graphMetrics(g:MorphGenome){return{nodes:g.nodes.length,edges:g.edges.length,massKg:g.nodes.reduce((a,n)=>a+n.massKg,0),compute:g.nodes.filter(n=>n.kind==="COMPUTE").reduce((a,n)=>a+n.capacity,0),thermal:g.nodes.filter(n=>n.kind==="THERMAL"||n.kind==="SURFACE").reduce((a,n)=>a+n.capacity,0),surfaceM2:g.nodes.reduce((a,n)=>a+n.areaM2,0)};}
