import {buildMorphGenome,graphMetrics,humanGraphH0,type MorphEdge,type MorphGenome,type MorphNode} from "./morphologyGenome.js";import type {MorphologyMode} from "./morphologyHomeostasis.js";import {evaluateEmbodiment} from "./functionalEmbodiment.js";import {evaluatePhysicalTasks} from "./physicalEmbodiment.js";
export type GraphEvolutionResult={mode:MorphologyMode;winner:MorphGenome;score:number;metrics:ReturnType<typeof graphMetrics>;mutationsAccepted:number};
function score(g:MorphGenome){const m=graphMetrics(g),body=evaluateEmbodiment(g),physics=evaluatePhysicalTasks(g);if(m.compute>900||m.thermal>1800||m.massKg>100||m.surfaceM2>4||!body.allRequiredPass||!physics.allPass)return -1e9;const conformity=g.mode==="H2_FREE"?0:g.humanConformity*35;const functionReward=body.profiles.reduce((a,p)=>a+p.score,0)*8+physics.score*55;return m.compute*.08+m.thermal*.035-m.massKg*1.2-m.nodes*.25-m.edges*.08+conformity+functionReward;}
function candidate(base:MorphGenome,mode:MorphologyMode,g:number,k:number):MorphGenome{
 const nodes:MorphNode[]=base.nodes.map(n=>({...n})),edges:MorphEdge[]=base.edges.map(e=>({...e}));const tag=g+"_"+k;
 if(mode!=="H0_HUMAN"){const compute=nodes.find(n=>n.kind==="COMPUTE"&&n.region==="torso");if(compute)compute.capacity*=k%2===0?1.03:.99;const thermal=nodes.find(n=>n.kind==="THERMAL");if(thermal)thermal.capacity*=k%3===0?1.04:.995;}
 if(mode==="H2_FREE"){
  if((g+k)%7===0&&nodes.length<44){const region="support_"+tag,sid="s_"+region,aid="a_"+region,qid="q_"+region;nodes.push({id:sid,kind:"STRUCTURE",region,massKg:3.2,capacity:1,areaM2:.08},{id:aid,kind:"ACTUATOR",region,massKg:.9,capacity:130,areaM2:.02},{id:qid,kind:"SENSOR",region,massKg:.12,capacity:40,areaM2:.02});edges.push({a:"core",b:sid,kind:"MECHANICAL",capacity:1},{a:"core",b:aid,kind:"POWER",capacity:130},{a:"core",b:qid,kind:"DATA",capacity:40});}
  if((g+k)%11===0&&nodes.length<44){const region="manip_"+tag,sid="s_"+region,aid="a_"+region,qid="q_"+region;nodes.push({id:sid,kind:"STRUCTURE",region,massKg:2.4,capacity:1,areaM2:.07},{id:aid,kind:"ACTUATOR",region,massKg:.8,capacity:110,areaM2:.02},{id:qid,kind:"SENSOR",region,massKg:.1,capacity:40,areaM2:.02});edges.push({a:"core",b:sid,kind:"MECHANICAL",capacity:1},{a:"core",b:aid,kind:"POWER",capacity:110},{a:"core",b:qid,kind:"DATA",capacity:40});}
  if((g+k)%3===0&&nodes.length<44){const id="x_"+tag,kind=k%2===0?"THERMAL":"COMPUTE";nodes.push({id,kind,region:"free_"+tag,massKg:kind==="COMPUTE"?.7:.5,capacity:kind==="COMPUTE"?45:65,areaM2:kind==="THERMAL"?.1:.03});edges.push({a:"core",b:id,kind:kind==="THERMAL"?"FLUID":"DATA",capacity:65});}
  if((g+k)%5===0){const victim=nodes.find(n=>n.kind==="STRUCTURE"&&n.region!=="torso");if(victim){const regionIds=new Set(nodes.filter(n=>n.region===victim.region).map(n=>n.id));for(let i=nodes.length-1;i>=0;i--)if(regionIds.has(nodes[i]!.id))nodes.splice(i,1);for(let i=edges.length-1;i>=0;i--)if(regionIds.has(edges[i]!.a)||regionIds.has(edges[i]!.b))edges.splice(i,1);}}
 }
 return buildMorphGenome({mode,generation:g,humanConformity:mode==="H0_HUMAN"?1:mode==="H1_BIO_INSPIRED"?.85:0,nodes,edges,lineageRefs:[base.id,"graph-evolution:v0"]});
}
export function evolveGraph(mode:MorphologyMode,generations=20,population=12):GraphEvolutionResult{if(generations<1||generations>100||population<2||population>64)throw new Error("graph_evolution_bounds");const h=humanGraphH0();let best=mode==="H0_HUMAN"?h:buildMorphGenome({mode,generation:0,humanConformity:mode==="H1_BIO_INSPIRED"?.85:0,nodes:h.nodes,edges:h.edges,lineageRefs:[h.id,"mode-release:v0"]}),bestScore=score(best),accepted=0;for(let g=1;g<=generations;g++)for(let k=0;k<population;k++){const c=candidate(best,mode,g,k),s=score(c);if(s>bestScore){best=c;bestScore=s;accepted++;}}return Object.freeze({mode,winner:best,score:Number(bestScore.toFixed(6)),metrics:graphMetrics(best),mutationsAccepted:accepted});}
