import type {AnnualBuildingScore} from './coupledBuildingEnergyTwin.js';
export type BuildingArchetype='DETACHED_HOUSE'|'APARTMENT_BLOCK'|'OFFICE'|'RETAIL'|'WAREHOUSE'|'INDUSTRIAL';
export type RetrofitPackage={id:string;archetype:BuildingArchetype;measures:readonly string[];evidenceRefs:readonly string[];capexEur:number;embodiedCarbonKg:number};
export type RankedRetrofit={packageId:string;weatherRefs:readonly string[];seedCount:number;median:AnnualBuildingScore;robustness:number;worstCaseEnergyKWh:number;worstCaseDiscomfortHours:number;truthState:'SIMULATED';authorityEffect:'NONE'};
export function generateRetrofitPackages(archetype:BuildingArchetype){const skins=[['INSULATION'],['BAMBOO_SCREEN','VENTILATED_CAVITY'],['RADIATIVE_COATING','INSULATION'],['PCM_GEL','INSULATION'],['NANO_COOL_COATING','PCM_GEL','INSULATION']];const systems=[['AIR_SOURCE_HP','PV'],['GROUND_SOURCE_HP','PV','THERMAL_STORAGE'],['AIR_SOURCE_HP','PEROVSKITE_TANDEM','THERMAL_STORAGE'],['HIGH_TEMP_HP','WASTE_HEAT_RECOVERY','PV']];return skins.flatMap((s,i)=>systems.map((e,j)=>({id:`${archetype.toLowerCase()}-${i}-${j}`,archetype,measures:[...s,...e,'MPC'],evidenceRefs:[],capexEur:0,embodiedCarbonKg:0})))}
const med=(xs:number[])=>{const a=[...xs].sort((x,y)=>x-y);return a.length%2?a[(a.length-1)/2]!:(a[a.length/2-1]!+a[a.length/2]!)/2};
export function aggregateRobustness(packageId:string,runs:readonly AnnualBuildingScore[],weatherRefs:readonly string[],seedCount:number):RankedRetrofit{if(!runs.length||weatherRefs.length<2||seedCount<2)throw Error('multi_weather_multi_seed_required');const numeric=(k:keyof AnnualBuildingScore)=>runs.map(r=>Number(r[k]));const template=runs[0]!;const median:AnnualBuildingScore={...template,scenarioId:packageId,annualSiteEnergyKWh:med(numeric('annualSiteEnergyKWh')),peakGridKW:med(numeric('peakGridKW')),discomfortHours:med(numeric('discomfortHours')),capexEur:med(numeric('capexEur')),annualMaintenanceEur:med(numeric('annualMaintenanceEur')),embodiedCarbonKg:med(numeric('embodiedCarbonKg')),resilience:med(numeric('resilience')),manufacturability:med(numeric('manufacturability'))};const energy=numeric('annualSiteEnergyKWh'),comfort=numeric('discomfortHours');const spread=(xs:number[])=>Math.max(...xs)-Math.min(...xs);const robustness=1/(1+(spread(energy)/(med(energy)||1))+(spread(comfort)/(med(comfort)||1)));return{packageId,weatherRefs:[...new Set(weatherRefs)],seedCount,median,worstCaseEnergyKWh:Math.max(...energy),worstCaseDiscomfortHours:Math.max(...comfort),robustness,truthState:'SIMULATED',authorityEffect:'NONE'}}
export function rankRobustRetrofits(xs:readonly RankedRetrofit[]){return [...xs].sort((a,b)=>b.robustness-a.robustness||a.worstCaseEnergyKWh-b.worstCaseEnergyKWh||a.median.capexEur-b.median.capexEur)}
export const retrofitCampaign={archetypes:['DETACHED_HOUSE','APARTMENT_BLOCK','OFFICE','RETAIL','WAREHOUSE','INDUSTRIAL'] as const,minimumWeatherYears:2,minimumSeeds:2,requiresMeasuredBaselineBeforePhysicalClaim:true,authorityEffect:'NONE' as const};
