export type TwinDataKind='WEATHER'|'SOLAR'|'WIND'|'HUMIDITY'|'MATERIAL'|'GEOMETRY'|'OCCUPANCY'|'METER'|'LITERATURE'|'SIMULATION_RESULT';
export type TwinDataSource={id:string;kind:TwinDataKind;provider:string;locator:string;licenseRef:string;provenanceRoot:string;quality:'MEASURED_QC'|'REFERENCE'|'LITERATURE'|'SYNTHETIC';refresh:'STATIC'|'DAILY'|'ON_DEMAND';parser:string};
export const buildingTwinSources:readonly TwinDataSource[]=[
{id:'dwd-hourly-temperature',kind:'WEATHER',provider:'DWD CDC',locator:'CDC/observations_germany/climate/hourly/air_temperature',licenseRef:'DWD-open-data-terms',provenanceRoot:'DWD-CDC',quality:'MEASURED_QC',refresh:'DAILY',parser:'DWD_HOURLY'},
{id:'dwd-hourly-solar',kind:'SOLAR',provider:'DWD CDC',locator:'CDC/observations_germany/climate/hourly/solar',licenseRef:'DWD-open-data-terms',provenanceRoot:'DWD-CDC',quality:'MEASURED_QC',refresh:'DAILY',parser:'DWD_HOURLY'},
{id:'dwd-hourly-wind',kind:'WIND',provider:'DWD CDC',locator:'CDC/observations_germany/climate/hourly/wind',licenseRef:'DWD-open-data-terms',provenanceRoot:'DWD-CDC',quality:'MEASURED_QC',refresh:'DAILY',parser:'DWD_HOURLY'},
{id:'dwd-hourly-moisture',kind:'HUMIDITY',provider:'DWD CDC',locator:'CDC/observations_germany/climate/hourly/moisture',licenseRef:'DWD-open-data-terms',provenanceRoot:'DWD-CDC',quality:'MEASURED_QC',refresh:'DAILY',parser:'DWD_HOURLY'},
{id:'dwd-try',kind:'WEATHER',provider:'DWD CDC',locator:'CDC/grids_germany/Project_TRY',licenseRef:'DWD-open-data-terms',provenanceRoot:'DWD-TRY',quality:'REFERENCE',refresh:'STATIC',parser:'DWD_TRY'},
{id:'energyplus-reference',kind:'SIMULATION_RESULT',provider:'DOE EnergyPlus',locator:'EnergyPlus-26.2-reference-cases',licenseRef:'EnergyPlus-license',provenanceRoot:'DOE-EPLUS',quality:'REFERENCE',refresh:'STATIC',parser:'EPLUS'},
{id:'lbl-modelica-reference',kind:'SIMULATION_RESULT',provider:'LBNL',locator:'Modelica-Buildings-14-reference-results',licenseRef:'Modelica-Buildings-license',provenanceRoot:'LBNL-BUILDINGS',quality:'REFERENCE',refresh:'STATIC',parser:'MODELICA'}];
export type IngestReceipt={sourceId:string;contentHash:string;retrievedAt:string;recordCount:number;schemaVersion:string;quality:TwinDataSource['quality'];truthState:'OBSERVED'|'EVIDENCE_SUPPORTED';authorityEffect:'NONE'};
export function validateReceipt(source:TwinDataSource,r:IngestReceipt){if(r.sourceId!==source.id||!r.contentHash||r.recordCount<1||!r.retrievedAt||!r.schemaVersion)throw Error('invalid_ingest_receipt');if(source.quality==='SYNTHETIC'&&r.truthState==='OBSERVED')throw Error('synthetic_cannot_be_observed');return true}
export function learningEligibility(source:TwinDataSource){return{sourceId:source.id,eligibleForCalibration:source.quality==='MEASURED_QC',eligibleForBenchmark:['MEASURED_QC','REFERENCE'].includes(source.quality),eligibleForWeightLearning:false,requiresEvidenceReview:true,authorityEffect:'NONE' as const}}
export const buildingTwinDataGate={webRetrievalIsUntrustedInput:true,promptInjectionScanningRequired:true,rawImmutable:true,hashEveryArtifact:true,parserSandboxRequired:true,sourceCannotGrantAuthority:true};
