import type {RetrofitRun} from './buildingEnvelopeWindTunnel.js';import type {EnergyRun} from './energySystemsWindTunnel.js';
export type AnnualBuildingScenario={id:string;weatherRef:string;buildingRef:string;occupancyRef:string;envelope:RetrofitRun;energy:EnergyRun;capexEur:number;annualMaintenanceEur:number;embodiedCarbonKg:number;truthState:'SIMULATED';authorityEffect:'NONE'};
export type AnnualBuildingScore={scenarioId:string;annualSiteEnergyKWh:number;annualUsefulHeatKWh:number;annualCoolingKWh:number;peakGridKW:number;discomfortHours:number;capexEur:number;annualMaintenanceEur:number;embodiedCarbonKg:number;resilience:number;manufacturability:number;truthState:'SIMULATED';authorityEffect:'NONE'};
export function validateAnnualScenario(x:AnnualBuildingScenario){const reasons:string[]=[];if(!x.weatherRef||!x.buildingRef||!x.occupancyRef)reasons.push('annual_context_missing');if(x.envelope.weatherRef!==x.weatherRef)reasons.push('weather_mismatch');if(x.capexEur<0||x.annualMaintenanceEur<0||x.embodiedCarbonKg<0)reasons.push('negative_cost_or_carbon');return{accepted:!reasons.length,reasons,authorityEffect:'NONE' as const}}
export function scoreAnnualScenario(x:AnnualBuildingScenario):AnnualBuildingScore{if(!validateAnnualScenario(x).accepted)throw Error('invalid_annual_scenario');const e=x.envelope.metrics,n=x.energy.metrics;return{scenarioId:x.id,annualSiteEnergyKWh:n.annualElectricityKWh,annualUsefulHeatKWh:e.annualHeatingKWh,annualCoolingKWh:e.annualCoolingKWh,peakGridKW:Math.max(e.peakHeatingKW+e.peakCoolingKW,n.peakGridKW),discomfortHours:e.overheatHours+e.coldDiscomfortHours,capexEur:x.capexEur,annualMaintenanceEur:x.annualMaintenanceEur,embodiedCarbonKg:x.embodiedCarbonKg,resilience:Math.min(e.resilience,n.resilience),manufacturability:n.manufacturability,truthState:'SIMULATED',authorityEffect:'NONE'}}
export type RetrofitObjective={key:keyof AnnualBuildingScore;direction:'MIN'|'MAX'};
export const annualObjectives:readonly RetrofitObjective[]=[{key:'annualSiteEnergyKWh',direction:'MIN'},{key:'peakGridKW',direction:'MIN'},{key:'discomfortHours',direction:'MIN'},{key:'capexEur',direction:'MIN'},{key:'annualMaintenanceEur',direction:'MIN'},{key:'embodiedCarbonKg',direction:'MIN'},{key:'resilience',direction:'MAX'},{key:'manufacturability',direction:'MAX'}];
const ge=(a:number,b:number,d:'MIN'|'MAX')=>d==='MIN'?a<=b:a>=b;
export function annualParetoFront(xs:readonly AnnualBuildingScore[],os:readonly RetrofitObjective[]=annualObjectives){return xs.filter(a=>!xs.some(b=>b!==a&&os.every(o=>ge(Number(b[o.key]),Number(a[o.key]),o.direction))&&os.some(o=>Number(b[o.key])!==Number(a[o.key]))))}
export function retrofitDelta(base:AnnualBuildingScore,c:AnnualBuildingScore){const pct=(a:number,b:number)=>a?100*(a-b)/a:0;return{siteEnergyPct:pct(base.annualSiteEnergyKWh,c.annualSiteEnergyKWh),peakPct:pct(base.peakGridKW,c.peakGridKW),discomfortPct:pct(base.discomfortHours,c.discomfortHours),capexDeltaEur:c.capexEur-base.capexEur,carbonDeltaKg:c.embodiedCarbonKg-base.embodiedCarbonKg,truthState:'SIMULATED' as const,authorityEffect:'NONE' as const}}
export const coupledAnnualWindTunnel={couples:['BUILDING_ENVELOPE','HVAC','PV','THERMAL_MANAGEMENT','STORAGE','CONTROL'] as const,requires:['HOURLY_WEATHER','BUILDING_BASELINE','OCCUPANCY_PROFILE','MULTI_SEED','ABLATION'] as const,seasonal:true,physicalClaim:false,autonomousLiveControl:false,authorityEffect:'NONE' as const};
