export type EnergyTech='INVERTER_AC'|'AIR_SOURCE_HP'|'GROUND_SOURCE_HP'|'HIGH_TEMP_HP'|'SILICON_PV'|'PEROVSKITE_PV'|'PEROVSKITE_TANDEM'|'PV_THERMAL'|'THERMAL_STORAGE'|'BATTERY'|'WASTE_HEAT_RECOVERY';
export type ThermalManagement='NONE'|'RADIATIVE'|'LIQUID'|'HEAT_PIPE'|'PCM';
export type EnergyArchitecture={id:string;technologies:readonly EnergyTech[];thermalManagement:ThermalManagement;sourceTempC:number;sinkTempC:number;pvCellTempC:number;storageKWh:number;control:'RULE'|'MPC'|'BAYESIAN';evidenceRefs:readonly string[]};
export type EnergyMetrics={annualUsefulHeatKWh:number;annualElectricityKWh:number;annualCoolingKWh:number;capexIndex:number;degradationIndex:number;peakGridKW:number;resilience:number;manufacturability:number};
export type EnergyRun={architectureId:string;seed:number;baselineId:string;metrics:EnergyMetrics;truthState:'SIMULATED';authorityEffect:'NONE'};
export type ParetoObjective={key:keyof EnergyMetrics;direction:'MIN'|'MAX'};
export const defaultEnergyObjectives:readonly ParetoObjective[]=[{key:'annualUsefulHeatKWh',direction:'MAX'},{key:'annualElectricityKWh',direction:'MIN'},{key:'capexIndex',direction:'MIN'},{key:'degradationIndex',direction:'MIN'},{key:'peakGridKW',direction:'MIN'},{key:'resilience',direction:'MAX'},{key:'manufacturability',direction:'MAX'}];
export function validateEnergyArchitecture(a:EnergyArchitecture){const reasons:string[]=[];if(!a.id.trim())reasons.push('id_missing');if(a.sinkTempC<=a.sourceTempC)reasons.push('invalid_temperature_lift');if(a.pvCellTempC< -100||a.pvCellTempC>150)reasons.push('pv_temperature_out_of_scope');if(a.storageKWh<0)reasons.push('storage_negative');if((a.technologies.includes('PEROVSKITE_PV')||a.technologies.includes('PEROVSKITE_TANDEM'))&&!a.evidenceRefs.length)reasons.push('perovskite_requires_evidence_anchor');return{accepted:!reasons.length,reasons,authorityEffect:'NONE' as const}}
const better=(a:EnergyMetrics,b:EnergyMetrics,o:ParetoObjective)=>o.direction==='MAX'?a[o.key]>=b[o.key]:a[o.key]<=b[o.key];
export function paretoFront(runs:readonly EnergyRun[],objectives:readonly ParetoObjective[]=defaultEnergyObjectives){return runs.filter(a=>!runs.some(b=>b!==a&&objectives.every(o=>better(b.metrics,a.metrics,o))&&objectives.some(o=>b.metrics[o.key]!==a.metrics[o.key])))}
export function classifyGain(candidate:EnergyRun,baseline:EnergyRun,objectives:readonly ParetoObjective[]=defaultEnergyObjectives){if(candidate.truthState!=='SIMULATED'||baseline.truthState!=='SIMULATED')throw Error('simulation_only');const noWorse=objectives.every(o=>better(candidate.metrics,baseline.metrics,o));const improved=objectives.some(o=>candidate.metrics[o.key]!==baseline.metrics[o.key]&&better(candidate.metrics,baseline.metrics,o));return{outcome:noWorse&&improved?'SIMULATED_GAIN' as const:'TRANSFER_REJECTED' as const,authorityEffect:'NONE' as const}}
export const energyWindTunnel={scope:['BUILDING','COMMERCIAL','INDUSTRIAL_PROCESS'] as const,search:['TOPOLOGY','SIZING','TEMPERATURES','THERMAL_MANAGEMENT','STORAGE','CONTROL'] as const,multiSeedRequired:true,baselineRequired:true,physicalClaim:false,autonomousLiveControl:false,authorityEffect:'NONE' as const};
