import {evaluateWall,type CompositeLayer,type CompositeMaterial,type WallResult} from './compositeWallWindTunnel.js';
export type LayerRole='EXTERNAL_SCREEN'|'VENTILATED_CAVITY'|'COOL_SKIN'|'INSULATION'|'THERMAL_BUFFER'|'STRUCTURAL'|'SERVICE';
export type LayerGene={role:LayerRole;material:CompositeMaterial;thicknessOptionsMm:readonly number[];properties:Omit<CompositeLayer,'material'|'thicknessMm'>};
export type SandwichCandidate={id:string;genes:readonly {role:LayerRole;layer:CompositeLayer}[];wall:WallResult;truthState:'SIMULATED';authorityEffect:'NONE'};
export function evolveSandwiches(genes:readonly LayerGene[],maxCandidates=500){if(!genes.length||maxCandidates<1)throw Error('invalid_search');let states:readonly {role:LayerRole;layer:CompositeLayer}[][]=[[]];for(const g of genes){const next:{role:LayerRole;layer:CompositeLayer}[][]=[];for(const s of states)for(const t of g.thicknessOptionsMm){if(t<=0)continue;next.push([...s,{role:g.role,layer:{material:g.material,thicknessMm:t,...g.properties}}]);if(next.length>=maxCandidates)break}states=next.slice(0,maxCandidates);if(!states.length)break}return states.map((x,i)=>{const wall=evaluateWall({id:'sandwich-'+i,layers:x.map(y=>y.layer),surfaceResistanceM2KW:.17,areaM2:1});return{id:wall.id,genes:x,wall,truthState:'SIMULATED' as const,authorityEffect:'NONE' as const}})}
export function thermalBufferPosition(c:SandwichCandidate){return c.genes.findIndex(x=>x.role==='THERMAL_BUFFER')}
export function positionAblations(c:SandwichCandidate){const i=thermalBufferPosition(c);if(i<0)return[];const g=c.genes[i]!;return c.genes.map((_,j)=>j).filter(j=>j!==i).map(j=>{const x=[...c.genes];x.splice(i,1);x.splice(j,0,g);return{x,position:j}})}
export function sandwichPareto(xs:readonly SandwichCandidate[]){return xs.filter(a=>!xs.some(b=>b!==a&&b.wall.uValueWm2K<=a.wall.uValueWm2K&&b.wall.materialCostEurM2<=a.wall.materialCostEurM2&&b.wall.embodiedCarbonKgM2<=a.wall.embodiedCarbonKgM2&&b.wall.arealHeatCapacityKJm2K>=a.wall.arealHeatCapacityKJm2K&&(b.wall.uValueWm2K<a.wall.uValueWm2K||b.wall.materialCostEurM2<a.wall.materialCostEurM2||b.wall.embodiedCarbonKgM2<a.wall.embodiedCarbonKgM2||b.wall.arealHeatCapacityKJm2K>a.wall.arealHeatCapacityKJm2K)))}
export const sandwichEvolutionInvariant={positionIsExperimentalVariable:true,pcmPositionNeedsAnnualDynamicModel:true,ventilatedCavityNeedsAirflowModel:true,coolSkinNeedsSolarRadiativeModel:true,moistureFireStructureBeforeBuild:true,physicalClaim:false,authorityEffect:'NONE' as const};
