import {createHash} from 'node:crypto';

export type AdpAutomationMode='ASSISTED'|'PARTIAL'|'CONDITIONAL'|'HIGH'|'FULL'|'DRIVERLESS';
export type AdpEvidenceKind='SIMULATION'|'TRACK'|'ROAD'|'AUTHORITY_VERIFIED';
export type AdpStatus='DRAFT'|'EXAM_READY'|'QUALIFIED'|'RESTRICTED'|'SUSPENDED'|'EXPIRED';
export type AdpRequirement={id:string;source:string;sourceVersion:string;clause:string;text:string;oddApplicability:Record<string,unknown>;capabilityId:string;requiredEvidence:readonly AdpEvidenceKind[];passCriteria:Record<string,unknown>;provenanceRefs:readonly string[]};
export type AdpEvidence={id:string;kind:AdpEvidenceKind;systemVersion:string;requirementId:string;capabilityId:string;odd:Record<string,unknown>;scenarioIds:readonly string[];examiner:string;independent:boolean;heldOut:boolean;result:'PASS'|'FAIL'|'INCONCLUSIVE';timestamp:string;provenanceRefs:readonly string[];contentHash:string};
export type AdpQualification={requirementId:string;capabilityId:string;status:'QUALIFIED'|'NOT_QUALIFIED'|'RESTRICTED';evidenceIds:readonly string[];limitations:readonly string[]};
export type AdpPassport={schema:'nyxa.adp.v0';passportId:string;systemId:string;manufacturer:string;systemVersion:string;hardwareVersion:string;automationMode:AdpAutomationMode;odd:Record<string,unknown>;qualifications:readonly AdpQualification[];status:AdpStatus;validFrom:string;validUntil?:string;authorityRefs:readonly string[];provenanceRefs:readonly string[];previousPassportHash?:string;passportHash:string};

const stable=(x:unknown):string=>{if(Array.isArray(x))return '['+x.map(stable).join(',')+']';if(x&&typeof x==='object')return '{'+Object.entries(x as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>JSON.stringify(k)+':'+stable(v)).join(',')+'}';return JSON.stringify(x);};
export const hashRecord=(x:unknown)=>createHash('sha256').update(stable(x)).digest('hex');
export function sealEvidence(x:Omit<AdpEvidence,'contentHash'>):AdpEvidence{return{...x,contentHash:hashRecord(x)}}
export function verifyEvidence(e:AdpEvidence){const{contentHash,...body}=e;return contentHash===hashRecord(body)}
export function validateRequirement(r:AdpRequirement){if(!r.id||!r.source||!r.sourceVersion||!r.clause||!r.capabilityId||!r.provenanceRefs.length)throw new Error('adp_requirement_incomplete');if(!r.requiredEvidence.length)throw new Error('adp_requirement_evidence_required');return r}
export function evidenceSatisfies(r:AdpRequirement,e:AdpEvidence,systemVersion:string){return verifyEvidence(e)&&e.result==='PASS'&&e.systemVersion===systemVersion&&e.requirementId===r.id&&e.capabilityId===r.capabilityId&&r.requiredEvidence.includes(e.kind)&&e.provenanceRefs.length>0}
export function qualify(r:AdpRequirement,evidence:readonly AdpEvidence[],systemVersion:string):AdpQualification{const valid=evidence.filter(e=>evidenceSatisfies(r,e,systemVersion));const kinds=new Set(valid.map(e=>e.kind));const complete=r.requiredEvidence.every(k=>kinds.has(k));const independent=valid.some(e=>e.independent);const real=r.requiredEvidence.some(k=>k==='ROAD'||k==='TRACK'||k==='AUTHORITY_VERIFIED');const realIndependent=!real||valid.some(e=>e.independent&&(e.kind==='ROAD'||e.kind==='TRACK'||e.kind==='AUTHORITY_VERIFIED'));return{requirementId:r.id,capabilityId:r.capabilityId,status:complete&&independent&&realIndependent?'QUALIFIED':'NOT_QUALIFIED',evidenceIds:valid.map(e=>e.id),limitations:complete&&independent&&realIndependent?[]:['insufficient_independent_evidence']}}
export function issuePassport(input:Omit<AdpPassport,'schema'|'passportHash'>):AdpPassport{if(!input.provenanceRefs.length)throw new Error('adp_passport_provenance_required');if(input.qualifications.some(q=>q.status==='QUALIFIED')&&!input.authorityRefs.length)throw new Error('adp_authority_required');const body={schema:'nyxa.adp.v0' as const,...input};return{...body,passportHash:hashRecord(body)}}
export function verifyPassport(p:AdpPassport){const{passportHash,...body}=p;return passportHash===hashRecord(body)}
