import type {AdpRequirement} from './adp.js';
export const afgbvVerifiedSeeds:readonly AdpRequirement[]=[
{id:'AFGBV-A1-7.2-ODD-HAZARDS',source:'AFGBV Anlage 1',sourceVersion:'2026-10-07 verified current text',clause:'Teil 1 Nr. 7.2',text:'ODD-relevante gefährliche Szenarien und Ereignisse systematisch identifizieren und risikobewerten',oddApplicability:{autonomousOperation:true},capabilityId:'hazard_analysis',requiredEvidence:['ROAD','SIMULATION'],passCriteria:{hazardsIdentified:true,riskAnalysis:true},provenanceRefs:['official:gesetze-im-internet:afgbv:anlage1:7.2']},
{id:'AFGBV-A1-10-COVERAGE',source:'AFGBV Anlage 1',sourceVersion:'2026-10-07 verified current text',clause:'Teil 1 Nr. 10',text:'Ausreichende Testabdeckung für Szenarien, Testparameter und Umwelteinflüsse begründen und empirisch validieren',oddApplicability:{autonomousOperation:true},capabilityId:'test_coverage',requiredEvidence:['ROAD','SIMULATION'],passCriteria:{coverageJustified:true,empiricalValidation:true},provenanceRefs:['official:gesetze-im-internet:afgbv:anlage1:10']},
{id:'AFGBV-A1-10.2-REALROAD',source:'AFGBV Anlage 1',sourceVersion:'2026-10-07 verified current text',clause:'Teil 1 Nr. 10.2',text:'Fahrtests im realen Straßenverkehr, ergänzt durch Simulation und Testgelände',oddApplicability:{autonomousOperation:true},capabilityId:'real_world_validation',requiredEvidence:['ROAD','SIMULATION','TRACK'],passCriteria:{realRoad:true,simulation:true,testTrack:true},provenanceRefs:['official:gesetze-im-internet:afgbv:anlage1:10.2']},
{id:'AFGBV-A1-11-SIMVALID',source:'AFGBV Anlage 1',sourceVersion:'2026-10-07 verified current text',clause:'Teil 1 Nr. 11',text:'Simulationswerkzeuge gegen repräsentative reale Versuche validieren',oddApplicability:{autonomousOperation:true},capabilityId:'simulation_validation',requiredEvidence:['SIMULATION','ROAD'],passCriteria:{representativeRealComparison:true,noSignificantMetricDifference:true},provenanceRefs:['official:gesetze-im-internet:afgbv:anlage1:11']},
{id:'AFGBV-A1-11-3PARAM',source:'AFGBV Anlage 1',sourceVersion:'2026-10-07 verified current text',clause:'Teil 1 Nr. 11',text:'Jedes relevante gefährliche Szenario zumindest simulieren und mindestens drei Parameterkonstellationen prüfen',oddApplicability:{autonomousOperation:true},capabilityId:'hazard_scenario_examination',requiredEvidence:['SIMULATION'],passCriteria:{minimumParameterConstellations:3},provenanceRefs:['official:gesetze-im-internet:afgbv:anlage1:11']},
{id:'STVG-1G-MANDATORY-DATA',source:'StVG',sourceVersion:'2026-10-07 verified current text',clause:'§ 1g',text:'Vorgeschriebene Betriebsdaten speichern und für gesetzlich bestimmte Überwachungszwecke bereitstellen',oddApplicability:{autonomousOperation:true},capabilityId:'regulatory_data',requiredEvidence:['AUTHORITY_VERIFIED'],passCriteria:{mandatoryDataCoverage:true},provenanceRefs:['official:gesetze-im-internet:stvg:1g']}
];
