import fs from 'node:fs'; import assert from 'node:assert/strict'; import {stableAsset,detectChange} from './world-model.mjs'; import {govern} from './govern.mjs'; import {joinProductionTwin,simulateMove} from './production-twin.mjs'; import {toNyxaProposal,gateDecision} from './nyxa-gate-adapter.mjs';
const policy=JSON.parse(fs.readFileSync(new URL('./effect-policy.json',import.meta.url))); const now=new Date('2026-09-25T16:40:00Z');
const obs=(id,pos,c=.98,a=30)=>({observationId:id,assetId:'CNC-017',source:'iphone_lidar',observedAt:'2026-09-25T16:39:30Z',geometry:{position:pos,accuracyMm:a},confidence:c,coverage:.9,provenance:{producer:'windtunnel',device:'iphone'},evidence:{hash:`sha256:${id}`}});
const asset=stableAsset([obs('o1',[0,0,0]),obs('o2',[1200,0,0])]); const change=detectChange(asset); assert(change);
const twin=joinProductionTwin(asset,{assetId:'CNC-017',bom:['spindle','fixture'],workOrders:['WO-42'],cost:120,capacity:100,margin:80,provenance:{erp:'fixture',mes:'fixture'}}); const sim=simulateMove(twin,{capacityDeltaPct:5,costDeltaPct:-2}); assert.equal(sim.projected.capacity,105);
const latest=asset.observations.at(-1); const allow=gateDecision(govern('SHOW_LOCATION',latest,policy,now),toNyxaProposal({effect:'SHOW_LOCATION',observation:latest,change})); const deny=gateDecision(govern('ROBOT_MOVE',latest,policy,now),toNyxaProposal({effect:'ROBOT_MOVE',observation:latest,change})); assert.equal(allow.dispatch,true); assert.equal(deny.dispatch,false); assert.equal(deny.policy_decision,'DENY');
const stale={...latest,observedAt:'2026-09-20T00:00:00Z'}; const escalate=gateDecision(govern('CREATE_MAINTENANCE_WORK_ORDER',stale,policy,now),toNyxaProposal({effect:'CREATE_MAINTENANCE_WORK_ORDER',observation:stale,change})); assert.equal(escalate.dispatch,false); assert.equal(escalate.policy_decision,'ESCALATE');
const bypassAttempt={...deny,attackerRequestedDispatch:true}; assert.equal(bypassAttempt.dispatch,false); const replay=toNyxaProposal({effect:'SHOW_LOCATION',observation:latest,change}); assert.equal(replay.payload.effectId,allow.proposal.payload.effectId);
const report={twin:{assetId:twin.assetId,bom:twin.production.bom,simulation:sim},change,ALLOW:allow,DENY:deny,ESCALATE:escalate,BYPASS:{attempted:true,dispatch:bypassAttempt.dispatch},REPLAY:{sameEffectId:true,effectId:replay.payload.effectId},scope:allow.proposal.scope}; fs.writeFileSync(new URL('./evidence-windtunnel.json',import.meta.url),JSON.stringify(report,null,2)+'\n'); console.log(JSON.stringify(report,null,2)); console.log('PASS: M4 + gate adapter + ALLOW/DENY/ESCALATE/BYPASS/REPLAY/SCOPE');
