export type AuditEvent = {
  id: string;
  timestamp: string;
  actor: "mcp" | "user" | "agent" | "system";
  action: string;
  tool?: string;
  mode: string;
  backend: string;
  result: "allowed" | "blocked" | "error";
  details?: Record<string, unknown>;
  capability_class?: "I0" | "I1" | "I2" | "I3";
  policy_decision?: "ALLOWED" | "DENIED" | "REQUIRES_APPROVAL" | "INVALID" | "UNKNOWN";
  arguments_hash?: string;
  affected_resource?: string;
  duration_ms?: number;
  result_status?: string;
  previous_event_hash?: string;
  event_hash?: string;
  requesting_identity?: string;
};
